name: nebula
description: "A privacy-first, open-source music streaming app built with Flutter & Supabase."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  envied: ^1.3.2
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  # Audio Core
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.1
  just_audio_media_kit: ^2.0.0
  media_kit: ^1.1.10
  media_kit_libs_linux: ^1.1.10
  audio_service: ^0.18.12
  rxdart: ^0.27.7
  # Source
  youtube_explode_dart: ^3.0.5
  # State Management (Simple for now)
  provider: ^6.1.1
  # UI
  font_awesome_flutter: ^10.6.0 # For player icons
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  flutter_local_notifications: ^18.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  version: ^3.0.2
  open_filex: ^4.7.0
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
