name: nebula
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  envied: ^1.3.2
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  # Audio Core
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.1
  audio_service: ^0.18.12
  rxdart: ^0.27.7
  # Source
  youtube_explode_dart: ^3.0.5
  # State Management (Simple for now)
  provider: ^6.1.1
  # UI
  font_awesome_flutter: ^10.6.0 # For player icons
  http: ^1.6.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
